### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by txinto** [kxtells/tenma-serial#1]
Firstable, thanks a lot!

In readme you have the typical copy&paste error, easy to fix.

> Turn on the channel output
> 
> python tenmaControl.py -on /dev/ttyUSB0
> Turn OFF the channel output
> 
> python tenmaControl.py -on /dev/ttyUSB0

first example should be "--on" instead of "-on"
second example should be "--off" instead of "-on".

(please take care of the two "--") 

just for your information, I have two power supplies and these are the USB devices:

1. /dev/tty.usbmodem14111
2. /dev/tty.usbmodem14121

Thanks again.

Ens veiem!

**Comment by kxtells** [comment]
Already fixed by your PR.

Merci!
