### ISSUE TITLE
Memory overwritting

### ISSUE THREAD

**Issue by dagmcr** [kxtells/tenma-serial#4]
Hi :)

I have realized that if you want to save a configuration to a memory you need to change the memory first and before saving the configuration. If not, the command --save overwrites the current memory configuration.

As a workaround I use:
$ export mem=3
$ python tenmaControl.py --recall $mem /dev/ttyUSB1; python tenmaControl.py --save $mem -c 3000 -v 3000 /dev/ttyUSB1
$ export mem=1
$ python tenmaControl.py --recall $mem /dev/ttyUSB1; python tenmaControl.py --save $mem -c 1000 -v 1000 /dev/ttyUSB1

And then, to return to the memory 3:
$ export mem=3
$ python tenmaControl.py --recall $mem /dev/ttyUSB1

**Comment by kxtells** [comment]
Isn't this fixed on https://github.com/kxtells/tenma-serial/commit/268cadbc20870f5b95a4591518a3c6dd820f2bda ?
