### ISSUE TITLE
Add support for beep

### ISSUE THREAD

**Issue by debuti** [kxtells/tenma-serial#8]
Support for enableing and disabling beep would be pretty much appreciated

BEEP<Boolean>
Description：Turns on or off the beep. Boolean: boolean logic.
Example BEEP1 Turns on the beep.

**Comment by kxtells** [comment]
Hi @debuti 

Beeping only comes (at least in my unit) from manually pressing the buttons so I never bothered with it in the past.

It is not something difficult so I just added it this morning (you can see it in the repo and on pip version 0.2.0) with two new options `--beep-enable` and `--beep-disable`

Thanks for the suggestion :+1: 

Salut!

**Comment by debuti** [comment]
Thanks Jordi!! Really appreciated
